const fs = require("fs");
const lines = [];
const L = (s) => lines.push(s);

L('import { type FamilyState, type Person } from "./family";');
L('import { computeDistances, pedigreePath } from "./lineage";');
L('');
L('function genderOf(p: Person | undefined): Person["gender"] {');
L('  return p?.gender ?? "unknown";');
L('}');
L('function birthOf(p: Person | undefined): string {');
L('  return p?.birthYear ?? "";');
L('}');
L('function isElder(a: Person | undefined, b: Person | undefined): boolean | null {');
L('  const ya = birthOf(a);');
L('  const yb = birthOf(b);');
L('  if (!ya || !yb) return null;');
L('  return ya < yb;');
L('}');
L('function isSpouse(state: FamilyState, meId: string, personId: string): boolean {');
L('  return state.spouses.some(');
L('    (s) => (s.a === meId && s.b === personId) || (s.b === meId && s.a === personId)');
L('  );');
L('}');
L('function spouseIdsOf(state: FamilyState, id: string): string[] {');
L('  return state.spouses');
L('    .filter((s) => s.a === id || s.b === id)');
L('    .map((s) => (s.a === id ? s.b : s.a));');
L('}');
L('function childIdsOf(state: FamilyState, id: string): string[] {');
L('  const out: string[] = [];');
L('  for (const [cid, p] of Object.entries(state.parents)) {');
L('    if (p.fatherId === id || p.motherId === id) out.push(cid);');
L('  }');
L('  return out;');
L('}');
L('function shareParents(state: FamilyState, a: string, b: string): boolean {');
L('  const pa = state.parents[a];');
L('  const pb = state.parents[b];');
L('  if (!pa || !pb) return false;');
L('  return Boolean(');
L('    (pa.fatherId && pa.fatherId === pb.fatherId) ||');
L('    (pa.motherId && pa.motherId === pb.motherId)');
L('  );');
L('}');
L('');
L('export function ancestorTerm(path: string): string {');
L('  const n = path.length;');
L('  if (n === 0) return "我";');
L('  const lastFather = path.charAt(n - 1) === "F";');
L('  const viaFather = path.charAt(0) === "F";');
L('  if (n === 1) return lastFather ? "父亲" : "母亲";');
L('  const mid = n === 2 ? "" : n === 3 ? "曾" : n === 4 ? "高" : String(n - 2) + "世";');
L('  const core = lastFather ? "祖父" : "祖母";');
L('  return viaFather ? mid + core : "外" + mid + core;');
L('}');
L('');
L('function inLawParentTerm(me: Person, role: "father" | "mother"): string {');
L('  const meMale = genderOf(me) === "male";');
L('  if (role === "mother") return meMale ? "丈母娘" : "婆婆";');
L('  return meMale ? "岳父" : "公公";');
L('}');
L('');
L('export function kinshipTerm(');
L('  state: FamilyState,');
L('  personId: string,');
L('  meId: string | null');
L('): string {');
L('  if (!meId || !state.persons[meId] || !state.persons[personId]) return "亲属";');
L('  if (personId === meId) return "我";');
L('  const me = state.persons[meId];');
L('  const person = state.persons[personId];');
L('  const path = pedigreePath(state, personId, meId);');
L('  if (path && path.length > 0 && /^[FM]+$/.test(path)) {');
L('    return ancestorTerm(path);');
L('  }');
L('  return kinshipInner(state, personId, meId, me, person);');
L('}');
L('');
L('function kinshipInner(');
L('  state: FamilyState,');
L('  personId: string,');
L('  meId: string,');
L('  me: Person,');
L('  person: Person');
L('): string {');
L('  const mySpouses = spouseIdsOf(state, meId);');
L('  const gMe = genderOf(me);');
L('  const gP = genderOf(person);');
L('  const myP = state.parents[meId];');
L('');
L('  // 配偶');
L('  if (isSpouse(state, meId, personId)) {');
L('    if (gMe === "female" && gP === "male") return "丈夫";');
L('    if (gMe === "male" && gP === "female") return "妻子";');
L('    return "配偶";');
L('  }');
L('');
L('  // 子女');
L('  const myKids = childIdsOf(state, meId);');
L('  if (myKids.includes(personId)) {');
L('    if (gP === "male") return "儿子";');
L('    if (gP === "female") return "女儿";');
L('    return "子女";');
L('  }');
L('');
L('  // 儿媳 / 女婿');
L('  for (const kidId of myKids) {');
L('    if (isSpouse(state, kidId, personId)) {');
L('      const kid = state.persons[kidId];');
L('      if (genderOf(kid) === "male" && gP === "female") return "儿媳";');
L('      if (genderOf(kid) === "female" && gP === "male") return "女婿";');
L('      return "子女配偶";');
L('    }');
L('  }');
L('');
L('  // 配偶的父母：丈母娘/岳父/婆婆/公公');
L('  for (const sid of mySpouses) {');
L('    const sp = state.parents[sid];');
L('    if (!sp) continue;');
L('    if (sp.motherId === personId) return inLawParentTerm(me, "mother");');
L('    if (sp.fatherId === personId) return inLawParentTerm(me, "father");');
L('  }');
L('');
L('  // 配偶的兄弟姐妹');
L('  for (const sid of mySpouses) {');
L('    if (!shareParents(state, sid, personId)) continue;');
L('    const spouse = state.persons[sid];');
L('    const elder = isElder(person, spouse);');
L('    if (gMe === "male") {');
L('      if (gP === "male") {');
L('        if (elder === true) return "内兄";');
L('        if (elder === false) return "内弟";');
L('        return "妻兄弟";');
L('      }');
L('      if (elder === true) return "姨姐";');
L('      if (elder === false) return "姨妹";');
L('      return "妻姐妹";');
L('    }');
L('    if (gP === "male") {');
L('      if (elder === true) return "大伯子";');
L('      if (elder === false) return "小叔子";');
L('      return "夫兄弟";');
L('    }');
L('    if (elder === true) return "大姑子";');
L('    if (elder === false) return "小姑子";');
L('    return "夫姐妹";');
L('  }');
L('');
L('  // 同胞');
L('  const hisP = state.parents[personId];');
L('  if (myP && hisP && shareParents(state, meId, personId)) {');
L('    const elder = isElder(person, me);');
L('    if (gP === "male") {');
L('      return elder === true ? "哥哥" : elder === false ? "弟弟" : "兄弟";');
L('    }');
L('    if (gP === "female") {');
L('      return elder === true ? "姐姐" : elder === false ? "妹妹" : "姐妹";');
L('    }');
L('    return "同胞";');
L('  }');
L('');
L('  // 嫂子弟媳姐夫妹夫：与我同胞结婚的人');
L('  for (const sibId of Object.keys(state.persons)) {');
L('    if (sibId === meId || sibId === personId) continue;');
L('    if (!isSpouse(state, sibId, personId)) continue;');
L('    if (!myP || !shareParents(state, meId, sibId)) continue;');
L('    const sib = state.persons[sibId];');
L('    const sibMale = genderOf(sib) === "male";');
L('    const elder = isElder(sib, me);');
L('    if (sibMale && gP === "female") {');
L('      return elder === true ? "嫂子" : elder === false ? "弟媳" : "兄弟配偶";');
L('    }');
L('    if (!sibMale && gP === "male") {');
L('      return elder === true ? "姐夫" : elder === false ? "妹夫" : "姐妹配偶";');
L('    }');
L('  }');
L('');
L('  // 父母的兄弟姐妹');
L('  const parentsOfMe = [myP?.fatherId, myP?.motherId].filter(Boolean) as string[];');
L('  for (const parentId of parentsOfMe) {');
L('    if (!shareParents(state, parentId, personId)) continue;');
L('    const viaFather = parentId === myP?.fatherId;');
L('    if (viaFather) {');
L('      if (gP === "male") {');
L('        const elder = isElder(person, state.persons[parentId]);');
L('        return elder === true ? "伯父" : elder === false ? "叔父" : "叔伯";');
L('      }');
L('      return "姑母";');
L('    }');
L('    return gP === "male" ? "舅父" : "姨母";');
L('  }');
L('');
L('  // 侄甥：同胞的子女');
L('  for (const [cid, entry] of Object.entries(state.parents)) {');
L('    const pids = [entry.fatherId, entry.motherId].filter(Boolean) as string[];');
L('    if (!pids.includes(personId)) continue;');
L('    if (!myP || !shareParents(state, meId, cid)) continue;');
L('    const childG = genderOf(state.persons[cid]);');
L('    if (gMe === "male") return childG === "female" ? "侄女" : "侄子";');
L('    return childG === "female" ? "外甥女" : "外甥";');
L('  }');
L('');
L('  // 堂表亲：父母同胞的子女');
L('  if (hisP) {');
L('    const hisParents = [hisP.fatherId, hisP.motherId].filter(Boolean) as string[];');
L('    for (const mid of parentsOfMe) {');
L('      for (const pid of hisParents) {');
L('        if (!pid || !shareParents(state, mid, pid)) continue;');
L('        const fatherSibling = mid === myP?.fatherId || pid === myP?.fatherId;');
L('        const prefix = fatherSibling ? "堂" : "表";');
L('        if (gP === "male") return prefix + "兄弟";');
L('        if (gP === "female") return prefix + "姐妹";');
L('        return prefix + "亲";');
L('      }');
L('    }');
L('  }');
L('');
L('  // 孙辈');
L('  for (const kidId of myKids) {');
L('    const kp = state.parents[personId];');
L('    if (!kp) continue;');
L('    if (kp.fatherId === kidId || kp.motherId === kidId) {');
L('      const kid = state.persons[kidId];');
L('      const kidMale = genderOf(kid) === "male";');
L('      if (kidMale) return gP === "female" ? "孙女" : "孙子";');
L('      return gP === "female" ? "外孙女" : "外孙";');
L('    }');
L('  }');
L('');
L('  // 亲家');
L('  for (const kidId of myKids) {');
L('    for (const kSp of spouseIdsOf(state, kidId)) {');
L('      const kp = state.parents[kSp];');
L('      if (!kp) continue;');
L('      if (kp.fatherId === personId || kp.motherId === personId) {');
L('        return gP === "male" ? "亲家公" : "亲家母";');
L('      }');
L('    }');
L('  }');
L('');
L('  const d = computeDistances(state).get(personId);');
L('  if (d === null || d === undefined) return "亲属";');
L('  if (d === -1) return "父母";');
L('  if (d === 0) return "同辈";');
L('  if (d === 1) return "子女";');
L('  if (d < 0) return String(Math.abs(d)) + " 世祖";');
L('  return String(d) + " 世孙";');
L('}');
L('');
L('export function buildKinshipMap(');
L('  state: FamilyState,');
L('  meId: string | null');
L('): Map<string, string> {');
L('  const map = new Map<string, string>();');
L('  if (!meId || !state.persons[meId]) return map;');
L('  for (const id of Object.keys(state.persons)) {');
L('    map.set(id, kinshipTerm(state, id, meId));');
L('  }');
L('  return map;');
L('}');
L('');

fs.writeFileSync("D:/XiaomiMiMoProjects/laotagong/lib/kinship.ts", lines.join("\n"), "utf8");
console.log("kinship.ts written", lines.length);
