const fs = require("fs");
const lines = [];
const P = (s) => lines.push(s);
P('"use client";');
P("");
P("import { useEffect, useRef } from \"react\";");
P("import type { FamilyState } from \"@/lib/family\";");
P("import { buildKinshipMap } from \"@/lib/kinship\";");
P("import {");
P("  type LineageKind,");
P("  classifyLineage,");
P("  computeDistances,");
P("  filterVisibleIds,");
P("} from \"@/lib/lineage\";");
P("");
P("const G6_CDN = \"https://cdn.jsdelivr.net/npm/@antv/g6@5.0.49/dist/g6.min.js\";");
P("");
P("const LINEAGE_COLOR: Record<string, string> = {");
P("  ego: \"#2563eb\",");
P("  paternal: \"#0284c7\",");
P("  maternal: \"#c026d3\",");
P("  descendant: \"#059669\",");
P("  sibling: \"#64748b\",");
P("  affinal: \"#d97706\",");
P("  collateral: \"#64748b\",");
P("  orphan: \"#94a3b8\",");
P("};");
P("");
P("function nodeHtml(name: string, term: string, color: string): string {");
P("  const head = '<div style=\"width:148px;height:64px;border-radius:14px;background:linear-gradient(145deg,rgba(255,255,255,0.88),rgba(255,255,255,0.64));border:1px solid rgba(255,255,255,0.85);box-shadow:0 8px 24px rgba(15,23,42,0.12);border-left:3px solid ';");
P("  return head + color + ';padding:8px 10px;box-sizing:border-box;overflow:hidden;font-family:-apple-system,PingFang SC,sans-serif;\"><div style=\"font-size:13px;font-weight:600;color:#0f172a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;\">' + name + '</div><div style=\"font-size:11px;color:' + color + ';margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;\">' + term + '</div></div>';");
P("}");
P("");
P("function loadG6(): Promise<any> {");
P("  const w = window as any;");
P("  if (w.G6 && w.G6.Graph) return Promise.resolve(w.G6);");
P("  return new Promise((resolve, reject) => {");
P("    const existing = document.querySelector('script[data-g6]');");
P("    if (existing) {");
P("      existing.addEventListener('load', () => resolve((window as any).G6));");
P("      existing.addEventListener('error', () => reject(new Error('g6 script error')));");
P("      return;");
P("    }");
P("    const script = document.createElement('script');");
P("    script.src = G6_CDN;");
P("    script.async = true;");
P("    script.dataset.g6 = '1';");
P("    script.onload = () => resolve((window as any).G6);");
P("    script.onerror = () => reject(new Error('g6 script load failed'));");
P("    document.head.appendChild(script);");
P("  });");
P("}");
P("");
P("export function TreeG6({");
P("  state,");
P("  focusId,");
P("  filter,");
P("  maxDepth,");
P("  onOpenPerson,");
P("}: {");
P("  state: FamilyState;");
P("  focusId: string | null;");
P("  filter: \"all\" | \"paternal\" | \"maternal\" | \"direct\";");
P("  maxDepth: number;");
P("  onOpenPerson: (id: string) => void;");
P("}) {");
P("  const hostRef = useRef<HTMLDivElement>(null);");
P("  const graphRef = useRef<any>(null);");
P("  const openRef = useRef(onOpenPerson);");
P("  openRef.current = onOpenPerson;");
P("");
P("  useEffect(() => {");
P("    let disposed = false;");
P("    async function boot() {");
P("      const host = hostRef.current;");
P("      if (!host) return;");
P("      const G6 = await loadG6();");
P("      const Graph = G6?.Graph;");
P("      if (disposed || !hostRef.current || !Graph) return;");
P("");
P("      const visible = filterVisibleIds(state, filter, maxDepth);");
P("      const distances = computeDistances(state);");
P("      const kinship = buildKinshipMap(state, state.meId);");
P("      const meId = state.meId;");
P("      const nodes = [...visible].map((id) => {");
P("        const p = state.persons[id];");
P("        const lineage: LineageKind = meId ? classifyLineage(state, id, meId, distances) : \"orphan\";");
P("        return {");
P("          id,");
P("          data: {");
P("            name: p?.name ?? id,");
P("            term: kinship.get(id) || \"\",");
P("            lineage,");
P("            color: LINEAGE_COLOR[lineage] ?? LINEAGE_COLOR.orphan,");
P("          },");
P("        };");
P("      });");
P("      const nodeSet = new Set(nodes.map((n) => n.id));");
P("      const edges: any[] = [];");
P("      for (const [cid, entry] of Object.entries(state.parents)) {");
P("        if (!nodeSet.has(cid)) continue;");
P("        if (entry.fatherId && nodeSet.has(entry.fatherId)) {");
P("          edges.push({ id: \"ef-\" + entry.fatherId + \"-\" + cid, source: entry.fatherId, target: cid, data: { lineage: \"paternal\" } });");
P("        }");
P("        if (entry.motherId && nodeSet.has(entry.motherId)) {");
P("          edges.push({ id: \"em-\" + entry.motherId + \"-\" + cid, source: entry.motherId, target: cid, data: { lineage: \"maternal\" } });");
P("        }");
P("      }");
P("      for (const s of state.spouses) {");
P("        if (!nodeSet.has(s.a) || !nodeSet.has(s.b)) continue;");
P("        edges.push({ id: \"es-\" + s.a + \"-\" + s.b, source: s.a, target: s.b, data: { lineage: \"spouse\" } });");
P("      }");
P("      if (graphRef.current) {");
P("        try { graphRef.current.destroy(); } catch { /* ignore */ }");
P("        graphRef.current = null;");
P("      }");
P("      host.innerHTML = \"\";");
P("      const width = host.clientWidth || 360;");
P("      const height = host.clientHeight || 480;");
P("      const graph = new Graph({");
P("        container: host,");
P("        width,");
P("        height,");
P("        autoFit: \"view\",");
P("        padding: 24,");
P("        data: { nodes, edges },");
P("        node: {");
P("          type: \"html\",");
P("          style: {");
P("            size: [148, 64],");
P("            innerHTML: (d: any) => {");
P("              const n = d?.data ?? d ?? {};");
P("              return nodeHtml(String(n.name ?? d?.id ?? \"\"), String(n.term ?? \"\"), String(n.color ?? \"#64748b\"));");
P("            },");
P("          },");
P("        },");
P("        edge: {");
P("          type: \"line\",");
P("          style: {");
P("            stroke: (d: any) => {");
P("              const lin = d?.data?.lineage;");
P("              if (lin === \"spouse\") return \"#d97706\";");
P("              if (lin === \"maternal\") return \"#c026d3\";");
P("              return \"#0284c7\";");
P("            },");
P("            lineWidth: 1.6,");
P("          },");
P("        },");
P("        layout: { type: \"dagre\", rankdir: \"TB\", nodesep: 28, ranksep: 72 },");
P("        behaviors: [\"drag-canvas\", \"zoom-canvas\", \"drag-element\"],");
P("      });");
P("      graph.on(\"node:click\", (evt: any) => {");
P("        const id = evt?.target?.id ?? evt?.item?.id ?? evt?.data?.id;");
P("        if (id) openRef.current(String(id));");
P("      });");
P("      await graph.render();");
P("      graphRef.current = graph;");
P("    }");
P("    boot().catch((err) => {");
P("      console.error(\"G6 boot failed\", err);");
P("      if (hostRef.current) hostRef.current.innerHTML = '<div class=\"flex h-full items-center justify-center text-caption\">G6 unavailable offline</div>';");
P("    });");
P("    return () => {");
P("      disposed = true;");
P("      if (graphRef.current) {");
P("        try { graphRef.current.destroy(); } catch { /* ignore */ }");
P("        graphRef.current = null;");
P("      }");
P("    };");
P("  }, [state, filter, maxDepth, focusId]);");
P("");
P("  return (");
P("    <div");
P("      ref={hostRef}");
P("      data-tree-g6");
P("      className=\"relative min-h-0 flex-1 overflow-hidden rounded-3xl border border-[var(--glass-edge)] bg-[var(--glass)]/40\"");
P("      style={{ height: \"100%\", minHeight: 360 }}");
P("    />");
P("  );");
P("}");
P("");
fs.writeFileSync("D:/XiaomiMiMoProjects/laotagong/components/tree-g6.tsx", lines.join("\n"), "utf8");
console.log("g6 cdn ok");
